name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdownlint:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - name: Run Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: "**/*.md"

  links:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --root-dir . --verbose --no-progress './**/*.md'
          fail: true
          token: ${{ secrets.GITHUB_TOKEN }}
